# Generated by Django 4.0.3 on 2022-03-23 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='author_fk',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article_fk',
        ),
        migrations.AddField(
            model_name='article',
            name='comments_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.comment'),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='User',
        ),
        migrations.CreateModel(
            name='Commemt_second_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('author_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.user')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_second_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.commemt_second_level'),
            preserve_default=False,
        ),
    ]
