# Generated by Django 4.0.3 on 2022-03-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_usuario_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='photo',
            field=models.CharField(max_length=200),
        ),
    ]
