# Generated by Django 4.0.3 on 2022-03-25 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0005_alter_usuario_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='author_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.userprofile'),
        ),
        migrations.AlterField(
            model_name='commemt_second_level',
            name='author_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.userprofile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.userprofile'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
