# Generated by Django 4.0.3 on 2022-03-28 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_userprofile_alter_article_author_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_fk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='article.userprofile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_fk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='article.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='Comment_second_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('author_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='article.userprofile')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_second_level',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='article.comment_second_level'),
        ),
        migrations.DeleteModel(
            name='Commemt_second_level',
        ),
    ]
