# Generated by Django 4.0.3 on 2022-03-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_article_comments_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
