# Generated by Django 4.0.3 on 2022-03-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
