# Generated by Django 4.0.3 on 2022-03-28 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.userprofile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.userprofile'),
        ),
        migrations.AlterField(
            model_name='comment_second_level',
            name='author_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.userprofile'),
        ),
    ]
