# Generated by Django 4.0.3 on 2022-03-28 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_alter_comment_comment_second_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comments_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.comment'),
            preserve_default=False,
        ),
    ]
