# Generated by Django 4.0.3 on 2022-03-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_alter_comment_comment_second_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='comments_fk',
            new_name='comments',
        ),
    ]
