# Generated by Django 4.0.3 on 2022-03-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_rename_comments_fk_article_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='comments',
            new_name='comments_fk',
        ),
    ]
