# Generated by Django 4.0.3 on 2022-03-28 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_alter_comment_comment_second_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comments_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_second_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.comment_second_level'),
            preserve_default=False,
        ),
    ]
