# Generated by Django 4.0.3 on 2022-03-28 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_alter_article_comments_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comments_fk',
        ),
        migrations.AddField(
            model_name='comment',
            name='publicacion_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.article'),
            preserve_default=False,
        ),
    ]
