# Generated by Django 4.0.3 on 2022-03-28 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_remove_article_comments_fk_comment_publicacion_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_second_level',
        ),
        migrations.AddField(
            model_name='comment_second_level',
            name='comentario_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.comment'),
            preserve_default=False,
        ),
    ]
