# Generated by Django 4.0.3 on 2022-03-28 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0024_remove_comment_comment_second_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hearts',
        ),
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('hearts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.userprofile')),
            ],
        ),
    ]
