# Generated by Django 4.0.3 on 2022-03-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0025_remove_article_hearts_heart'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hearts',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Heart',
        ),
    ]
